#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null
set_up_symlinks
update_hgignore

echo
echo "--- Updating translations"
#$TOOLS_DIR/update_messages

echo
echo "--- Running Selenium tests"
$PYTHON $TOOLS_DIR/server_tests.py "$@"
