#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null
cd $APP_DIR
../tools/extract_messages ../tools/setup.py static/locale.js
$APPENGINE_DIR/lib/django/django/bin/compile-messages.py "$@"
$PYTHON -c 'import setup; setup.setup_js_messages()'
../tools/find_missing_translations
